// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVFsNPi2bs0pHwwYHjmvzQirHwGeI2Is',
    appId: '1:663430969060:web:44352ab89ee2536d32def1',
    messagingSenderId: '663430969060',
    projectId: 'auth-firebase-fbc09',
    authDomain: 'auth-firebase-fbc09.firebaseapp.com',
    storageBucket: 'auth-firebase-fbc09.appspot.com',
    measurementId: 'G-TWV5B9GT78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb7okzdyt1ZL5ayxw9gCdSe3ukMbR_jjI',
    appId: '1:663430969060:android:51b422076684c35f32def1',
    messagingSenderId: '663430969060',
    projectId: 'auth-firebase-fbc09',
    storageBucket: 'auth-firebase-fbc09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVfEuaeSphSkC1ce8-iVW2HOzmI5JaYlc',
    appId: '1:663430969060:ios:d881682d8bc6d31c32def1',
    messagingSenderId: '663430969060',
    projectId: 'auth-firebase-fbc09',
    storageBucket: 'auth-firebase-fbc09.appspot.com',
    iosClientId: '663430969060-e6qu92gk1n7usca0gntfu038o5lpbv1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVfEuaeSphSkC1ce8-iVW2HOzmI5JaYlc',
    appId: '1:663430969060:ios:ee1abf293ae82f9a32def1',
    messagingSenderId: '663430969060',
    projectId: 'auth-firebase-fbc09',
    storageBucket: 'auth-firebase-fbc09.appspot.com',
    iosClientId: '663430969060-cint1fig93t53g7u118gkqc6ed26asg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebase.RunnerTests',
  );
}
